RELIC_INFO = {
    "AKABEKO": {"name": "Akabeko", "description": "At the start of each combat, gain 8 Vigor.", "rarity": "Uncommon Relic"},
    "ALCHEMICAL_COFFER": {"name": "Alchemical Coffer", "description": "Upon pickup, gain 4 potion slots filled with random potions.", "rarity": "Ancient Relic"},
    "AMETHYST_AUBERGINE": {"name": "Amethyst Aubergine", "description": "Enemies drop 10 additional Gold.", "rarity": "Common Relic"},
    "ANCHOR": {"name": "Anchor", "description": "Start each combat with 10 Block.", "rarity": "Common Relic"},
    "ARCANE_SCROLL": {"name": "Arcane Scroll", "description": "Upon pickup, obtain a random Rare Card to add to your Deck.", "rarity": "Ancient Relic"},
    "ARCHAIC_TOOTH": {"name": "Archaic Tooth", "description": "Upon pickup, Transform a starter card with an ancient version.", "rarity": "Ancient Relic"},
    "ART_OF_WAR": {"name": "Art of War", "description": "If you do not play any Attacks during your turn, gain an additional [energy:1] next turn.", "rarity": "Rare Relic"},
    "ASTROLABE": {"name": "Astrolabe", "description": "Upon pickup, Transform 3 cards, then Upgrade them.", "rarity": "Ancient Relic"},
    "BAG_OF_MARBLES": {"name": "Bag of Marbles", "description": "At the start of each combat, apply 1 Vulnerable to ALL enemies.", "rarity": "Uncommon Relic"},
    "BAG_OF_PREPARATION": {"name": "Bag of Preparation", "description": "At the start of each combat, draw 2 additional cards.", "rarity": "Common Relic"},
    "BEATING_REMNANT": {"name": "Beating Remnant", "description": "You cannot lose more than 20 HP in a single turn.", "rarity": "Rare Relic"},
    "BEAUTIFUL_BRACELET": {"name": "Beautiful Bracelet", "description": "Upon pickup, choose 3 cards in your Deck. Enchant them with [purple]Swift[/purple] 3.", "rarity": "Ancient Relic"},
    "BELLOWS": {"name": "Bellows", "description": "The first Hand you draw each combat is Upgraded.", "rarity": "Uncommon Relic"},
    "BELT_BUCKLE": {"name": "Belt Buckle", "description": "While you have no potions, you have 2 additional Dexterity.", "rarity": "Shop Relic"},
    "BIG_HAT": {"name": "Big Hat", "description": "At the start of each combat, add 2 random Ethereal cards into your Hand.", "rarity": "Rare Relic"},
    "BIG_MUSHROOM": {"name": "Big Mushroom", "description": "Upon pickup, raise your Max HP by 20. At the start of each combat, draw 2 fewer cards.", "rarity": "Event Relic"},
    "BIIIG_HUG": {"name": "Biiig Hug", "description": "Upon pickup, remove 4 cards from your Deck. Whenever you shuffle your Draw Pile, add a Soot into your Draw Pile.", "rarity": "Ancient Relic"},
    "BING_BONG": {"name": "Bing Bong", "description": "Whenever you add a card to your Deck, add one additional copy.", "rarity": "Event Relic"},
    "BLACK_BLOOD": {"name": "Black Blood", "description": "At the end of combat, heal [green]12[/green] HP.", "rarity": "Starter Relic"},
    "BLACK_STAR": {"name": "Black Star", "description": "Elites drop an additional Relic when defeated.", "rarity": "Ancient Relic"},
    "BLESSED_ANTLER": {"name": "Blessed Antler", "description": "Gain [energy:1] at the start of each turn. At the start of each combat, shuffle 3 Dazed into your Draw Pile.", "rarity": "Ancient Relic"},
    "BLOOD_SOAKED_ROSE": {"name": "Blood-Soaked Rose", "description": "Upon pickup, add 1 [red]Enthralled[/red] to your Deck. Gain [energy:1] at the start of each turn.", "rarity": "Ancient Relic"},
    "BLOOD_VIAL": {"name": "Blood Vial", "description": "At the start of each combat, heal [green]2[/green] HP.", "rarity": "Common Relic"},
    "BONE_FLUTE": {"name": "Bone Flute", "description": "Whenever Osty attacks, gain 2 Block.", "rarity": "Common Relic"},
    "BONE_TEA": {"name": "Bone Tea", "description": "At the start of the next combat, Upgrade your starting hand.", "rarity": "Event Relic"},
    "BOOKMARK": {"name": "Bookmark", "description": "At the end of each turn, lower the cost of a random Retained card by 1 until played.", "rarity": "Rare Relic"},
    "BOOK_OF_FIVE_RINGS": {"name": "Book of Five Rings", "description": "Every 5 cards you add to your Deck, heal [green]15[/green] HP.", "rarity": "Common Relic"},
    "BOOK_REPAIR_KNIFE": {"name": "Book Repair Knife", "description": "Whenever a non-Minion enemy dies to Doom, heal [green]3[/green] HP.", "rarity": "Uncommon Relic"},
    "BOOMING_CONCH": {"name": "Booming Conch", "description": "At the start of Elite combats, draw 2 additional cards.", "rarity": "Ancient Relic"},
    "BOUND_PHYLACTERY": {"name": "Bound Phylactery", "description": "At the start of your turn, Summon 1.", "rarity": "Starter Relic"},
    "BOWLER_HAT": {"name": "Bowler Hat", "description": "Gain 20% additional Gold.", "rarity": "Uncommon Relic"},
    "BREAD": {"name": "Bread", "description": "At the start of your first turn, lose [energy:2]. At the start of all other turns, gain [energy:1].", "rarity": "Shop Relic"},
    "BRILLIANT_SCARF": {"name": "Brilliant Scarf", "description": "The 5th card you play each turn is free.", "rarity": "Ancient Relic"},
    "BRIMSTONE": {"name": "Brimstone", "description": "At the start of your turn, gain 2 Strength and ALL enemies gain 1 Strength.", "rarity": "Shop Relic"},
    "BRONZE_SCALES": {"name": "Bronze Scales", "description": "Start each combat with 3 Thorns.", "rarity": "Common Relic"},
    "BURNING_BLOOD": {"name": "Burning Blood", "description": "At the end of combat, heal [green]6[/green] HP.", "rarity": "Starter Relic"},
    "BURNING_STICKS": {"name": "Burning Sticks", "description": "The first time each combat you Exhaust a Skill, add a copy of it into your Hand.", "rarity": "Shop Relic"},
    "BYRDPIP": {"name": "Byrdpip", "description": "Upon pickup, gain the card Byrd Swoop. A Byrdpip will accompany you in battles.", "rarity": "Event Relic"},
    "CALLING_BELL": {"name": "Calling Bell", "description": "Upon pickup, obtain a unique [red]Curse[/red] and 3 Relics.", "rarity": "Ancient Relic"},
    "CANDELABRA": {"name": "Candelabra", "description": "At the start of your 2nd turn, gain [energy:2].", "rarity": "Uncommon Relic"},
    "CAPTAINS_WHEEL": {"name": "Captain's Wheel", "description": "At the start of your 3rd turn, gain 18 Block.", "rarity": "Rare Relic"},
    "CAULDRON": {"name": "Cauldron", "description": "Upon pickup, brews 5 random potions.", "rarity": "Shop Relic"},
    "CENTENNIAL_PUZZLE": {"name": "Centennial Puzzle", "description": "The first time you lose HP each combat, draw 3 cards.", "rarity": "Common Relic"},
    "CHANDELIER": {"name": "Chandelier", "description": "At the start of your 3rd turn, gain [energy:3].", "rarity": "Rare Relic"},
    "CHARONS_ASHES": {"name": "Charon's Ashes", "description": "Whenever you Exhaust a card, deal 3 damage to ALL enemies.", "rarity": "Rare Relic"},
    "CHEMICAL_X": {"name": "Chemical X", "description": "The effects of your cost X cards are increased by 2.", "rarity": "Shop Relic"},
    "CHOICES_PARADOX": {"name": "Choices Paradox", "description": "At the start of each combat, add 1 of 5 random cards into your Hand. Add Retain to the chosen card.", "rarity": "Ancient Relic"},
    "CHOSEN_CHEESE": {"name": "The Chosen Cheese", "description": "At the end of combat, gain 1 Max HP.", "rarity": "Event Relic"},
    "CIRCLET": {"name": "Circlet", "description": "It's a circlet.", "rarity": "Relic"},
    "CLAWS": {"name": "Claws", "description": "Upon pickup, Transform up to 6 cards into Maul.", "rarity": "Ancient Relic"},
    "CLOAK_CLASP": {"name": "Cloak Clasp", "description": "At the end of your turn, gain 1 Block for each card in your Hand.", "rarity": "Rare Relic"},
    "CRACKED_CORE": {"name": "Cracked Core", "description": "At the start of each combat, Channel 1 Lightning.", "rarity": "Starter Relic"},
    "CROSSBOW": {"name": "Crossbow", "description": "At the start of your turn, add a random Attack into your Hand. It costs 0[energy:1] this turn.", "rarity": "Ancient Relic"},
    "CURSED_PEARL": {"name": "Cursed Pearl", "description": "Upon pickup, receive [red]Greed[/red]. Gain 333 Gold.", "rarity": "Ancient Relic"},
    "DARKSTONE_PERIAPT": {"name": "Darkstone Periapt", "description": "Whenever you obtain a [red]Curse[/red], raise your Max HP by 6.", "rarity": "Event Relic"},
    "DATA_DISK": {"name": "Data Disk", "description": "Start each combat with 1 Focus.", "rarity": "Common Relic"},
    "DAUGHTER_OF_THE_WIND": {"name": "Daughter of the Wind", "description": "Whenever you play an Attack, gain 1 Block.", "rarity": "Event Relic"},
    "DELICATE_FROND": {"name": "Delicate Frond", "description": "At the start of each combat, fill all empty potion slots with random potions.", "rarity": "Ancient Relic"},
    "DEMON_TONGUE": {"name": "Demon Tongue", "description": "The first time you lose HP on your turn, heal HP equal to the amount lost.", "rarity": "Rare Relic"},
    "DIAMOND_DIADEM": {"name": "Diamond Diadem", "description": "Whenever you play 2 or fewer cards in a turn, take half damage from enemies.", "rarity": "Ancient Relic"},
    "DINGY_RUG": {"name": "Dingy Rug", "description": "Card rewards can now contain Colorless cards.", "rarity": "Shop Relic"},
    "DISTINGUISHED_CAPE": {"name": "Distinguished Cape", "description": "Upon pickup, lose [red]9[/red] Max HP. Add 3 Apparitions to your Deck.", "rarity": "Ancient Relic"},
    "DIVINE_DESTINY": {"name": "Divine Destiny", "description": "At the start of each combat, gain [star:6].", "rarity": "Starter Relic"},
    "DIVINE_RIGHT": {"name": "Divine Right", "description": "At the start of each combat, gain [star:3].", "rarity": "Starter Relic"},
    "DOLLYS_MIRROR": {"name": "Dolly's Mirror", "description": "Upon pickup, obtain an additional copy of a card in your Deck.", "rarity": "Shop Relic"},
    "DRAGON_FRUIT": {"name": "Dragon Fruit", "description": "Whenever you gain Gold, raise your Max HP by 1.", "rarity": "Shop Relic"},
    "DREAM_CATCHER": {"name": "Dream Catcher", "description": "Whenever you Rest, you may add a card to your Deck.", "rarity": "Event Relic"},
    "DRIFTWOOD": {"name": "Driftwood", "description": "You may reroll each card reward once.", "rarity": "Ancient Relic"},
    "DUSTY_TOME": {"name": "Dusty Tome", "description": "Upon pickup, obtain an Ancient Card.", "rarity": "Ancient Relic"},
    "ECTOPLASM": {"name": "Ectoplasm", "description": "You can no longer gain Gold. Gain [energy:1] at the start of each turn.", "rarity": "Ancient Relic"},
    "ELECTRIC_SHRYMP": {"name": "Electric Shrymp", "description": "Upon pickup, Enchant a Skill with [purple]Imbued[/purple].", "rarity": "Ancient Relic"},
    "EMBER_TEA": {"name": "Ember Tea", "description": "At the start of the next 5 combats, gain 2 Strength.", "rarity": "Event Relic"},
    "EMOTION_CHIP": {"name": "Emotion Chip", "description": "If you lost HP during the previous turn, trigger the passive ability of all Orbs at the start of your turn.", "rarity": "Rare Relic"},
    "EMPTY_CAGE": {"name": "Empty Cage", "description": "Upon pickup, remove 2 cards from your Deck.", "rarity": "Ancient Relic"},
    "ETERNAL_FEATHER": {"name": "Eternal Feather", "description": "For every 5 cards in your Deck, heal [green]3[/green] HP whenever you enter a Rest Site.", "rarity": "Uncommon Relic"},
    "FAKE_ANCHOR": {"name": "Anchor???", "description": "Start each combat with 4 Block.", "rarity": "Event Relic"},
    "FAKE_BLOOD_VIAL": {"name": "Blood Vial???", "description": "At the start of each combat, heal [green]1[/green] HP.", "rarity": "Event Relic"},
    "FAKE_HAPPY_FLOWER": {"name": "Happy Flower???", "description": "Every 5 turns, gain [energy:1].", "rarity": "Event Relic"},
    "FAKE_LEES_WAFFLE": {"name": "Lee's Waffle???", "description": "Upon pickup, heal [green]10%[/green] of your HP.", "rarity": "Event Relic"},
    "FAKE_MANGO": {"name": "Mango???", "description": "Upon pickup, raise your Max HP by 3.", "rarity": "Event Relic"},
    "FAKE_MERCHANTS_RUG": {"name": "The Merchant's Rug???", "description": "Poor imitation. Does nothing.", "rarity": "Event Relic"},
    "FAKE_ORICHALCUM": {"name": "Orichalcum???", "description": "If you end your turn without Block, gain 3 Block.", "rarity": "Event Relic"},
    "FAKE_SNECKO_EYE": {"name": "Snecko Eye???", "description": "Start each combat [red]Confused[/red].", "rarity": "Event Relic"},
    "FAKE_STRIKE_DUMMY": {"name": "Strike Dummy???", "description": "Cards containing “Strike” deal 1 additional damage.", "rarity": "Event Relic"},
    "FAKE_VENERABLE_TEA_SET": {"name": "Venerable Tea Set???", "description": "Whenever you enter a Rest Site, start the next combat with an additional [energy:1].", "rarity": "Event Relic"},
    "FENCING_MANUAL": {"name": "Fencing Manual", "description": "At the start of each combat, Forge 10.", "rarity": "Common Relic"},
    "FESTIVE_POPPER": {"name": "Festive Popper", "description": "At the start of each combat, deal 9 damage to ALL enemies.", "rarity": "Common Relic"},
    "FIDDLE": {"name": "Fiddle", "description": "At the start of each turn, draw 2 additional cards. You may not draw cards during your turn.", "rarity": "Ancient Relic"},
    "FORGOTTEN_SOUL": {"name": "Forgotten Soul", "description": "Whenever you Exhaust a card, deal 1 damage to a random enemy.", "rarity": "Event Relic"},
    "FRAGRANT_MUSHROOM": {"name": "Fragrant Mushroom", "description": "Upon pickup, lose [red]15[/red] HP and Upgrade 3 random cards.", "rarity": "Event Relic"},
    "FRESNEL_LENS": {"name": "Fresnel Lens", "description": "Whenever you add a card that gains Block to your Deck, Enchant it with [purple]Nimble[/purple] 2.", "rarity": "Event Relic"},
    "FROZEN_EGG": {"name": "Frozen Egg", "description": "Whenever you add a Power into your Deck, Upgrade it.", "rarity": "Rare Relic"},
    "FUNERARY_MASK": {"name": "Funerary Mask", "description": "At the start of each combat, add 3 Souls into your Draw Pile.", "rarity": "Uncommon Relic"},
    "FUR_COAT": {"name": "Fur Coat", "description": "Upon pickup, mark 7 random combats. Enemies in those rooms have 1 HP.", "rarity": "Ancient Relic"},
    "GALACTIC_DUST": {"name": "Galactic Dust", "description": "For every 10 [star:1] spent, gain 10 Block.", "rarity": "Uncommon Relic"},
    "GAMBLING_CHIP": {"name": "Gambling Chip", "description": "At the start of each combat, discard any number of cards then draw that many.", "rarity": "Rare Relic"},
    "GAME_PIECE": {"name": "Game Piece", "description": "Whenever you play a Power, draw 1 card.", "rarity": "Rare Relic"},
    "GHOST_SEED": {"name": "Ghost Seed", "description": "Strikes and Defends gain Ethereal.", "rarity": "Shop Relic"},
    "GIRYA": {"name": "Girya", "description": "You can now gain Strength at Rest Sites. (3 times max)", "rarity": "Rare Relic"},
    "GLASS_EYE": {"name": "Glass Eye", "description": "Upon pickup, obtain 2 Common cards, 2 Uncommon cards, and 1 Rare card.", "rarity": "Ancient Relic"},
    "GLITTER": {"name": "Glitter", "description": "Enchant all card rewards with [purple]Glam[/purple].", "rarity": "Ancient Relic"},
    "GNARLED_HAMMER": {"name": "Gnarled Hammer", "description": "Upon pickup, Enchant up to 3 Attacks with [purple]Sharp[/purple] 3.", "rarity": "Shop Relic"},
    "GOLDEN_COMPASS": {"name": "Golden Compass", "description": "Upon pickup, replace the Act 2 Map with a single special path.", "rarity": "Ancient Relic"},
    "GOLDEN_PEARL": {"name": "Golden Pearl", "description": "Upon pickup, gain 150 Gold.", "rarity": "Ancient Relic"},
    "GOLD_PLATED_CABLES": {"name": "Gold-Plated Cables", "description": "Your rightmost Orb triggers its passive an additional time.", "rarity": "Uncommon Relic"},
    "GORGET": {"name": "Gorget", "description": "At the start of each combat, gain 4 Plating.", "rarity": "Common Relic"},
    "GREMLIN_HORN": {"name": "Gremlin Horn", "description": "Whenever an enemy dies, gain [energy:1] and draw 1 card.", "rarity": "Uncommon Relic"},
    "HAND_DRILL": {"name": "Hand Drill", "description": "Whenever you break an enemy's Block, apply 2 Vulnerable.", "rarity": "Event Relic"},
    "HAPPY_FLOWER": {"name": "Happy Flower", "description": "Every 3 turns, gain [energy:1].", "rarity": "Common Relic"},
    "HELICAL_DART": {"name": "Helical Dart", "description": "Whenever you play a Shiv, gain 1 Dexterity this turn.", "rarity": "Rare Relic"},
    "HISTORY_COURSE": {"name": "History Course", "description": "At the start of your turn, play a copy of your last played Attack or Skill.", "rarity": "Event Relic"},
    "HORN_CLEAT": {"name": "Horn Cleat", "description": "At the start of your 2nd turn, gain 14 Block.", "rarity": "Uncommon Relic"},
    "ICE_CREAM": {"name": "Ice Cream", "description": "Energy is now conserved between turns.", "rarity": "Rare Relic"},
    "INFUSED_CORE": {"name": "Infused Core", "description": "At the start of each combat, Channel 3 Lightning.", "rarity": "Starter Relic"},
    "INTIMIDATING_HELMET": {"name": "Intimidating Helmet", "description": "Whenever you play a card that costs [energy:2] or more, gain 4 Block.", "rarity": "Rare Relic"},
    "IRON_CLUB": {"name": "Iron Club", "description": "Every 4 cards you play, draw 1 card.", "rarity": "Ancient Relic"},
    "IVORY_TILE": {"name": "Ivory Tile", "description": "Whenever you play a card that costs [energy:3] or more, gain [energy:1].", "rarity": "Rare Relic"},
    "JEWELED_MASK": {"name": "Jeweled Mask", "description": "At the start of combat put a random Power from your Draw Pile into your Hand, it's free to play.", "rarity": "Ancient Relic"},
    "JEWELRY_BOX": {"name": "Jewelry Box", "description": "Upon pickup, add 1 Apotheosis to your Deck.", "rarity": "Ancient Relic"},
    "JOSS_PAPER": {"name": "Joss Paper", "description": "Every 5 times you Exhaust a card, draw 1 card.", "rarity": "Uncommon Relic"},
    "JUZU_BRACELET": {"name": "Juzu Bracelet", "description": "Regular enemy combats are no longer encountered in ? rooms.", "rarity": "Common Relic"},
    "KIFUDA": {"name": "Kifuda", "description": "Upon pickup, Enchant up to 3 cards with [purple]Adroit[/purple].", "rarity": "Shop Relic"},
    "KUNAI": {"name": "Kunai", "description": "Every time you play 3 Attacks in a single turn, gain 1 Dexterity.", "rarity": "Rare Relic"},
    "KUSARIGAMA": {"name": "Kusarigama", "description": "Every time you play 3 Attacks in a single turn, deal 6 damage to a random enemy.", "rarity": "Uncommon Relic"},
    "LANTERN": {"name": "Lantern", "description": "Start each combat with an additional [energy:1].", "rarity": "Common Relic"},
    "LARGE_CAPSULE": {"name": "Large Capsule", "description": "Upon pickup, obtain 2 random Relics. Add an additional Strike and Defend to your Deck.", "rarity": "Ancient Relic"},
    "LASTING_CANDY": {"name": "Lasting Candy", "description": "Every other combat, your card rewards gain an additional Power.", "rarity": "Rare Relic"},
    "LAVA_LAMP": {"name": "Lava Lamp", "description": "At the end of combat, Upgrade all card rewards if you took no damage.", "rarity": "Shop Relic"},
    "LAVA_ROCK": {"name": "Lava Rock", "description": "The Act 1 Boss drops 2 Relics.", "rarity": "Ancient Relic"},
    "LEAD_PAPERWEIGHT": {"name": "Lead Paperweight", "description": "Upon pickup, choose 1 of 2 Colorless cards to add to your Deck.", "rarity": "Ancient Relic"},
    "LEAFY_POULTICE": {"name": "Leafy Poultice", "description": "Upon pickup, Transform 1 of your Strikes and 1 of your Defends and lose 10 Max HP.", "rarity": "Ancient Relic"},
    "LEES_WAFFLE": {"name": "Lee's Waffle", "description": "Upon pickup, raise your Max HP by 7 and heal all of your HP.", "rarity": "Shop Relic"},
    "LETTER_OPENER": {"name": "Letter Opener", "description": "Every time you play 3 Skills in a single turn, deal 5 damage to ALL enemies.", "rarity": "Uncommon Relic"},
    "LIZARD_TAIL": {"name": "Lizard Tail", "description": "When you would die, heal to [green]50%[/green] of your Max HP instead (works once).", "rarity": "Rare Relic"},
    "LOOMING_FRUIT": {"name": "Looming Fruit", "description": "Upon pickup, raise your Max HP by 31.", "rarity": "Ancient Relic"},
    "LORDS_PARASOL": {"name": "Lord's Parasol", "description": "When you encounter the Merchant, immediately obtain EVERYTHING he sells.", "rarity": "Ancient Relic"},
    "LOST_COFFER": {"name": "Lost Coffer", "description": "Upon pickup, gain 1 card reward and procure 1 random potion.", "rarity": "Ancient Relic"},
    "LOST_WISP": {"name": "Lost Wisp", "description": "Whenever you play a Power, deal 8 damage to ALL enemies.", "rarity": "Event Relic"},
    "LUCKY_FYSH": {"name": "Lucky Fysh", "description": "Whenever you add a card to your Deck, gain 15 Gold.", "rarity": "Uncommon Relic"},
    "LUNAR_PASTRY": {"name": "Lunar Pastry", "description": "At the end of your turn, gain [star:1].", "rarity": "Rare Relic"},
    "MANGO": {"name": "Mango", "description": "Upon pickup, raise your Max HP by 14.", "rarity": "Rare Relic"},
    "MASSIVE_SCROLL": {"name": "Massive Scroll", "description": "Upon pickup, choose 1 of 3 Multiplayer Cards to add to your Deck.", "rarity": "Ancient Relic"},
    "MAW_BANK": {"name": "Maw Bank", "description": "Whenever you climb a floor, gain 12 Gold. No longer works when you spend any Gold at the shop.", "rarity": "Event Relic"},
    "MEAL_TICKET": {"name": "Meal Ticket", "description": "Whenever you enter a shop room, heal [green]15[/green] HP.", "rarity": "Common Relic"},
    "MEAT_CLEAVER": {"name": "Meat Cleaver", "description": "You may Cook at Rest Sites.", "rarity": "Ancient Relic"},
    "MEAT_ON_THE_BONE": {"name": "Meat on the Bone", "description": "If your HP is at or below 50% at the end of combat, heal [green]12[/green] HP.", "rarity": "Rare Relic"},
    "MEMBERSHIP_CARD": {"name": "Membership Card", "description": "50% discount on all products!", "rarity": "Shop Relic"},
    "MERCURY_HOURGLASS": {"name": "Mercury Hourglass", "description": "At the start of your turn, deal 3 damage to ALL enemies.", "rarity": "Uncommon Relic"},
    "METRONOME": {"name": "Metronome", "description": "The first time you Channel 7 Orbs each combat, deal 30 damage to ALL enemies.", "rarity": "Rare Relic"},
    "MINIATURE_CANNON": {"name": "Miniature Cannon", "description": "Upgraded Attacks deal 3 additional damage.", "rarity": "Uncommon Relic"},
    "MINIATURE_TENT": {"name": "Miniature Tent", "description": "You may choose any number of options at Rest Sites.", "rarity": "Shop Relic"},
    "MINI_REGENT": {"name": "Mini Regent", "description": "The first time you spend [star:1] each turn, gain 1 Strength.", "rarity": "Rare Relic"},
    "MOLTEN_EGG": {"name": "Molten Egg", "description": "Whenever you add an Attack card to your Deck, Upgrade it.", "rarity": "Rare Relic"},
    "MR_STRUGGLES": {"name": "Mr. Struggles", "description": "At the start of your turn, deal damage equal to the turn number to ALL enemies.", "rarity": "Event Relic"},
    "MUMMIFIED_HAND": {"name": "Mummified Hand", "description": "Whenever you play a Power, a random card in your Hand is free to play that turn.", "rarity": "Rare Relic"},
    "MUSIC_BOX": {"name": "Music Box", "description": "Create an Ethereal copy of the first Attack you play each turn.", "rarity": "Ancient Relic"},
    "MYSTIC_LIGHTER": {"name": "Mystic Lighter", "description": "Enchanted Attacks deal 9 additional damage.", "rarity": "Shop Relic"},
    "NEOWS_TORMENT": {"name": "Neow's Torment", "description": "Upon pickup, add 1 Neow's Fury to your Deck.", "rarity": "Ancient Relic"},
    "NEW_LEAF": {"name": "New Leaf", "description": "Upon pickup, Transform 1 card.", "rarity": "Ancient Relic"},
    "NINJA_SCROLL": {"name": "Ninja Scroll", "description": "At the start of each combat, add 3 Shivs into your Hand.", "rarity": "Shop Relic"},
    "NUNCHAKU": {"name": "Nunchaku", "description": "Every time you play 10 Attacks, gain [energy:1].", "rarity": "Uncommon Relic"},
    "NUTRITIOUS_OYSTER": {"name": "Nutritious Oyster", "description": "Upon pickup, raise your Max HP by 11.", "rarity": "Ancient Relic"},
    "NUTRITIOUS_SOUP": {"name": "Nutritious Soup", "description": "Upon pickup, Enchant all Strikes in your Deck with [purple]Tezcatara's Ember[/purple].", "rarity": "Ancient Relic"},
    "ODDLY_SMOOTH_STONE": {"name": "Oddly Smooth Stone", "description": "Start each combat with 1 Dexterity.", "rarity": "Common Relic"},
    "OLD_COIN": {"name": "Old Coin", "description": "Upon pickup, gain 300 Gold.", "rarity": "Rare Relic"},
    "ORANGE_DOUGH": {"name": "Orange Dough", "description": "At the start of each combat, add 2 random Colorless cards into your Hand.", "rarity": "Rare Relic"},
    "ORICHALCUM": {"name": "Orichalcum", "description": "If you end your turn without Block, gain 6 Block.", "rarity": "Uncommon Relic"},
    "ORNAMENTAL_FAN": {"name": "Ornamental Fan", "description": "Every time you play 3 Attacks in a single turn, gain 4 Block.", "rarity": "Uncommon Relic"},
    "ORRERY": {"name": "Orrery", "description": "Upon pickup, gain 5 card rewards.", "rarity": "Shop Relic"},
    "PAELS_BLOOD": {"name": "Pael's Blood", "description": "At the start of your turn, draw 1 additional card.", "rarity": "Ancient Relic"},
    "PAELS_CLAW": {"name": "Pael's Claw", "description": "Upon pickup, Enchant all Defends with [purple]Goopy[/purple].", "rarity": "Ancient Relic"},
    "PAELS_EYE": {"name": "Pael's Eye", "description": "The first time each combat you end your turn without playing cards, Exhaust your Hand, and take an extra turn.", "rarity": "Ancient Relic"},
    "PAELS_FLESH": {"name": "Pael's Flesh", "description": "Gain an additional [energy:1] at the start of your 3rd turn, and every turn after that.", "rarity": "Ancient Relic"},
    "PAELS_GROWTH": {"name": "Pael's Growth", "description": "Upon pickup, Enchant a card with [purple]Clone[/purple].", "rarity": "Ancient Relic"},
    "PAELS_HORN": {"name": "Pael's Horn", "description": "Upon pickup, add 2 Relax to your Deck.", "rarity": "Ancient Relic"},
    "PAELS_LEGION": {"name": "Pael's Legion", "description": "Doubles Block gained from a card, then goes to sleep for 2 turns.", "rarity": "Ancient Relic"},
    "PAELS_TEARS": {"name": "Pael's Tears", "description": "If you end your turn with unspent [energy:1], gain an additional [energy:2] next turn.", "rarity": "Ancient Relic"},
    "PAELS_TOOTH": {"name": "Pael's Tooth", "description": "Upon pickup, remove 5 cards from your Deck. After each combat, randomly add 1 back Upgraded.", "rarity": "Ancient Relic"},
    "PAELS_WING": {"name": "Pael's Wing", "description": "You may sacrifice card rewards to Pael. Every 2 sacrifices, obtain a Relic.", "rarity": "Ancient Relic"},
    "PANDORAS_BOX": {"name": "Pandora's Box", "description": "Transform ALL Strikes and Defends.", "rarity": "Ancient Relic"},
    "PANTOGRAPH": {"name": "Pantograph", "description": "At the start of each Boss combat, heal [green]25[/green] HP.", "rarity": "Uncommon Relic"},
    "PAPER_KRANE": {"name": "Paper Krane", "description": "Enemies with Weak deal 40% less damage to you rather than 25%.", "rarity": "Rare Relic"},
    "PAPER_PHROG": {"name": "Paper Phrog", "description": "Enemies with Vulnerable take 75% more damage rather than 50%.", "rarity": "Uncommon Relic"},
    "PARRYING_SHIELD": {"name": "Parrying Shield", "description": "If you end a turn with at least 10 Block, deal 6 damage to a random enemy.", "rarity": "Uncommon Relic"},
    "PEAR": {"name": "Pear", "description": "Upon pickup, raise your Max HP by 10.", "rarity": "Uncommon Relic"},
    "PENDULUM": {"name": "Pendulum", "description": "Whenever you shuffle your Draw Pile, draw a card.", "rarity": "Common Relic"},
    "PEN_NIB": {"name": "Pen Nib", "description": "Every 10th Attack you play deals double damage.", "rarity": "Uncommon Relic"},
    "PERMAFROST": {"name": "Permafrost", "description": "The first time you play a Power each combat, gain 6 Block.", "rarity": "Common Relic"},
    "PETRIFIED_TOAD": {"name": "Petrified Toad", "description": "At the start of each combat, procure a Potion-Shaped Rock.", "rarity": "Uncommon Relic"},
    "PHILOSOPHERS_STONE": {"name": "Philosopher's Stone", "description": "Gain [energy:1] at the start of each turn. ALL enemies start combat with 1 Strength.", "rarity": "Ancient Relic"},
    "PHYLACTERY_UNBOUND": {"name": "Phylactery Unbound", "description": "At the start of each combat, Summon 5. At the start of your turn, Summon 2.", "rarity": "Starter Relic"},
    "PLANISPHERE": {"name": "Planisphere", "description": "Whenever you enter a ? room, heal [green]4[/green] HP.", "rarity": "Uncommon Relic"},
    "POCKETWATCH": {"name": "Pocketwatch", "description": "Whenever you play 3 or fewer cards during your turn, draw 3 additional cards at the start of your next turn.", "rarity": "Rare Relic"},
    "POLLINOUS_CORE": {"name": "Pollinous Core", "description": "Every 4 turns, draw 2 additional cards.", "rarity": "Event Relic"},
    "POMANDER": {"name": "Pomander", "description": "Upon pickup, Upgrade a card.", "rarity": "Ancient Relic"},
    "POTION_BELT": {"name": "Potion Belt", "description": "Upon pickup, gain 2 potion slots.", "rarity": "Common Relic"},
    "POWER_CELL": {"name": "Power Cell", "description": "At the start of each combat, add 2 zero-cost cards from your Draw Pile into your Hand.", "rarity": "Rare Relic"},
    "PRAYER_WHEEL": {"name": "Prayer Wheel", "description": "Normal enemies drop an additional card reward.", "rarity": "Rare Relic"},
    "PRECARIOUS_SHEARS": {"name": "Precarious Shears", "description": "Upon pickup, remove 2 cards from your Deck and take [red]13[/red] damage.", "rarity": "Ancient Relic"},
    "PRECISE_SCISSORS": {"name": "Precise Scissors", "description": "Upon pickup, remove 1 card from your Deck.", "rarity": "Ancient Relic"},
    "PRESERVED_FOG": {"name": "Preserved Fog", "description": "Upon pickup, remove 5 cards from your Deck. Add [red]Folly[/red] to your Deck.", "rarity": "Ancient Relic"},
    "PRISMATIC_GEM": {"name": "Prismatic Gem", "description": "Gain [energy:1] at the start of each turn. Card rewards now contain cards from other colors.", "rarity": "Ancient Relic"},
    "PUMPKIN_CANDLE": {"name": "Pumpkin Candle", "description": "Gain [energy:1] at the start of each turn. Extinguishes at the start of Act 3.", "rarity": "Ancient Relic"},
    "PUNCH_DAGGER": {"name": "Punch Dagger", "description": "Upon pickup, Enchant an Attack with [purple]Momentum[/purple] 5.", "rarity": "Shop Relic"},
    "RADIANT_PEARL": {"name": "Radiant Pearl", "description": "At the start of each combat, add 1 Luminesce into your Hand.", "rarity": "Ancient Relic"},
    "RAINBOW_RING": {"name": "Rainbow Ring", "description": "The first time you play an Attack, Skill, and Power each turn, gain 1 Strength and 1 Dexterity.", "rarity": "Rare Relic"},
    "RAZOR_TOOTH": {"name": "Razor Tooth", "description": "Every time you play an Attack or Skill, Upgrade it for the remainder of combat.", "rarity": "Rare Relic"},
    "RED_MASK": {"name": "Red Mask", "description": "At the start of each combat, apply 1 Weak to ALL enemies.", "rarity": "Uncommon Relic"},
    "RED_SKULL": {"name": "Red Skull", "description": "While your HP is at or below 50%, you have 3 additional Strength.", "rarity": "Common Relic"},
    "REGALITE": {"name": "Regalite", "description": "Whenever you create a Colorless card, gain 2 Block.", "rarity": "Uncommon Relic"},
    "REGAL_PILLOW": {"name": "Regal Pillow", "description": "Whenever you Rest, heal an additional 15 HP.", "rarity": "Common Relic"},
    "REPTILE_TRINKET": {"name": "Reptile Trinket", "description": "Whenever you use a potion, gain 3 Strength this turn.", "rarity": "Uncommon Relic"},
    "RINGING_TRIANGLE": {"name": "Ringing Triangle", "description": "Retain your Hand on the first turn of combat.", "rarity": "Shop Relic"},
    "RING_OF_THE_DRAKE": {"name": "Ring of the Drake", "description": "At the start of your first 3 turns, draw 2 additional cards.", "rarity": "Starter Relic"},
    "RING_OF_THE_SNAKE": {"name": "Ring of the Snake", "description": "At the start of each combat, draw 2 additional cards.", "rarity": "Starter Relic"},
    "RIPPLE_BASIN": {"name": "Ripple Basin", "description": "If you did not play any Attacks during your turn, gain 4 Block.", "rarity": "Uncommon Relic"},
    "ROYAL_POISON": {"name": "Royal Poison", "description": "At the start of each combat, lose 4 HP.", "rarity": "Event Relic"},
    "ROYAL_STAMP": {"name": "Royal Stamp", "description": "Upon pickup, choose an Attack or Skill in your Deck to Enchant with [purple]Royally Approved[/purple].", "rarity": "Shop Relic"},
    "RUINED_HELMET": {"name": "Ruined Helmet", "description": "The first time you gain Strength each combat, double the amount gained.", "rarity": "Rare Relic"},
    "RUNIC_CAPACITOR": {"name": "Runic Capacitor", "description": "Start each combat with 3 additional Orb Slots.", "rarity": "Shop Relic"},
    "RUNIC_PYRAMID": {"name": "Runic Pyramid", "description": "At the end of your turn, you no longer discard your Hand.", "rarity": "Ancient Relic"},
    "SAI": {"name": "Sai", "description": "At the start of your turn, gain 7 Block.", "rarity": "Ancient Relic"},
    "SAND_CASTLE": {"name": "Sand Castle", "description": "Upon pickup, Upgrade 6 random cards.", "rarity": "Ancient Relic"},
    "SCREAMING_FLAGON": {"name": "Screaming Flagon", "description": "If you end your turn with no cards in your Hand, deal 20 damage to ALL enemies.", "rarity": "Shop Relic"},
    "SCROLL_BOXES": {"name": "Scroll Boxes", "description": "Upon pickup, lose all Gold and choose 1 of 2 packs of cards to add to your Deck.", "rarity": "Ancient Relic"},
    "SEAL_OF_GOLD": {"name": "Seal of Gold", "description": "At the start of your turn, spend 5 Gold to gain [energy:1].", "rarity": "Ancient Relic"},
    "SEA_GLASS": {"name": "Sea Glass", "description": "See 15 cards from another character. Choose any number of them to add to your Deck.", "rarity": "Ancient Relic"},
    "SELF_FORMING_CLAY": {"name": "Self-Forming Clay", "description": "Whenever you lose HP in combat, gain 3 Block next turn.", "rarity": "Uncommon Relic"},
    "SERE_TALON": {"name": "Sere Talon", "description": "Upon pickup, add 2 random [red]Curses[/red] and 3 [purple]Wishes[/purple] to your Deck.", "rarity": "Ancient Relic"},
    "SHOVEL": {"name": "Shovel", "description": "You can now dig at Rest Sites to obtain a random Relic.", "rarity": "Rare Relic"},
    "SHURIKEN": {"name": "Shuriken", "description": "Every time you play 3 Attacks in a single turn, gain 1 Strength.", "rarity": "Rare Relic"},
    "SIGNET_RING": {"name": "Signet Ring", "description": "Upon pickup, gain 999 Gold.", "rarity": "Ancient Relic"},
    "SILVER_CRUCIBLE": {"name": "Silver Crucible", "description": "The first 3 card rewards you see are Upgraded. The first Treasure Chest you open is [red]empty[/red].", "rarity": "Ancient Relic"},
    "SLING_OF_COURAGE": {"name": "Sling of Courage", "description": "Start each Elite combat with 2 Strength.", "rarity": "Shop Relic"},
    "SMALL_CAPSULE": {"name": "Small Capsule", "description": "Upon pickup, obtain a random Relic.", "rarity": "Ancient Relic"},
    "SNECKO_EYE": {"name": "Snecko Eye", "description": "At the start of your turn, draw 2 additional cards. Start each combat [red]Confused[/red].", "rarity": "Ancient Relic"},
    "SNECKO_SKULL": {"name": "Snecko Skull", "description": "Whenever you apply Poison, apply an additional 1 Poison.", "rarity": "Common Relic"},
    "SOZU": {"name": "Sozu", "description": "Gain [energy:1] at the start of each turn. You can no longer obtain potions.", "rarity": "Ancient Relic"},
    "SPARKLING_ROUGE": {"name": "Sparkling Rouge", "description": "At the start of your 3rd turn, gain 1 Strength and 1 Dexterity.", "rarity": "Uncommon Relic"},
    "SPIKED_GAUNTLETS": {"name": "Spiked Gauntlets", "description": "Gain [energy:1] at the start of each turn. Powers cost 1 more [energy:1].", "rarity": "Ancient Relic"},
    "STONE_CALENDAR": {"name": "Stone Calendar", "description": "At the end of turn 7, deal 52 damage to ALL enemies.", "rarity": "Rare Relic"},
    "STONE_CRACKER": {"name": "Stone Cracker", "description": "At the start of Boss combats, Upgrade 3 random cards in your Draw Pile for the rest of combat.", "rarity": "Uncommon Relic"},
    "STONE_HUMIDIFIER": {"name": "Stone Humidifier", "description": "Whenever you Rest at a Rest Site, raise your Max HP by 5.", "rarity": "Ancient Relic"},
    "STORYBOOK": {"name": "Storybook", "description": "Upon pickup, add 1 Brightest Flame to your Deck.", "rarity": "Ancient Relic"},
    "STRAWBERRY": {"name": "Strawberry", "description": "Upon pickup, raise your Max HP by 7.", "rarity": "Common Relic"},
    "STRIKE_DUMMY": {"name": "Strike Dummy", "description": "Cards containing “Strike” deal 3 additional damage.", "rarity": "Common Relic"},
    "STURDY_CLAMP": {"name": "Sturdy Clamp", "description": "Up to 10 Block persists across turns.", "rarity": "Rare Relic"},
    "SWORD_OF_JADE": {"name": "Sword of Jade", "description": "Start each combat with 3 Strength.", "rarity": "Event Relic"},
    "SWORD_OF_STONE": {"name": "Sword of Stone", "description": "Transforms into a powerful Relic after defeating 5 Elites.", "rarity": "Event Relic"},
    "SYMBIOTIC_VIRUS": {"name": "Symbiotic Virus", "description": "At the start of each combat, Channel 1 Dark.", "rarity": "Uncommon Relic"},
    "TANXS_WHISTLE": {"name": "Tanx's Whistle", "description": "Upon pickup, add 1 Whistle to your Deck.", "rarity": "Ancient Relic"},
    "TEA_OF_DISCOURTESY": {"name": "Tea of Discourtesy", "description": "At the start of the next combat, shuffle 2 Dazed into your Draw Pile.", "rarity": "Event Relic"},
    "THE_ABACUS": {"name": "The Abacus", "description": "Whenever you shuffle your Draw Pile, gain 6 Block.", "rarity": "Shop Relic"},
    "THE_BOOT": {"name": "The Boot", "description": "Whenever you would deal 4 or less unblocked attack damage, increase it to 5.", "rarity": "Event Relic"},
    "THE_COURIER": {"name": "The Courier", "description": "The merchant no longer runs out of cards, relics, or potions and his prices are reduced by 20%.", "rarity": "Rare Relic"},
    "THROWING_AXE": {"name": "Throwing Axe", "description": "The first card you play each combat is played an extra time.", "rarity": "Ancient Relic"},
    "TINGSHA": {"name": "Tingsha", "description": "Whenever you discard a card during your turn, deal 3 damage to a random enemy for each card discarded.", "rarity": "Uncommon Relic"},
    "TINY_MAILBOX": {"name": "Tiny Mailbox", "description": "Whenever you Rest, procure a random potion.", "rarity": "Common Relic"},
    "TOASTY_MITTENS": {"name": "Toasty Mittens", "description": "At the start of your turn, Exhaust the top card of your Draw Pile and gain 1 Strength.", "rarity": "Ancient Relic"},
    "TOOLBOX": {"name": "Toolbox", "description": "At the start of each combat, choose 1 of 3 random Colorless cards and add the chosen card into your Hand.", "rarity": "Shop Relic"},
    "TOUCH_OF_OROBAS": {"name": "Touch of Orobas", "description": "Upon pickup, replace your starter Relic with an Ancient version.", "rarity": "Ancient Relic"},
    "TOUGH_BANDAGES": {"name": "Tough Bandages", "description": "Whenever you discard a card during your turn, gain 3 Block.", "rarity": "Rare Relic"},
    "TOXIC_EGG": {"name": "Toxic Egg", "description": "Whenever you add a Skill into your Deck, Upgrade it.", "rarity": "Rare Relic"},
    "TOY_BOX": {"name": "Toy Box", "description": "Upon pickup, obtain 4 Wax Relics. Every 3 combats, your left-most Wax Relic will melt away.", "rarity": "Ancient Relic"},
    "TRI_BOOMERANG": {"name": "Tri-Boomerang", "description": "Choose 3 Attacks in your Deck. Enchant them with [purple]Instinct[/purple].", "rarity": "Ancient Relic"},
    "TUNGSTEN_ROD": {"name": "Tungsten Rod", "description": "Whenever you would lose HP, lose 1 less.", "rarity": "Rare Relic"},
    "TUNING_FORK": {"name": "Tuning Fork", "description": "Every time you play 10 Skills, gain 7 Block.", "rarity": "Uncommon Relic"},
    "TWISTED_FUNNEL": {"name": "Twisted Funnel", "description": "At the start of each combat, apply 4 Poison to ALL enemies.", "rarity": "Uncommon Relic"},
    "UNCEASING_TOP": {"name": "Unceasing Top", "description": "Whenever you have no cards in Hand during your turn, draw a card.", "rarity": "Rare Relic"},
    "UNDYING_SIGIL": {"name": "Undying Sigil", "description": "Enemies with at least as much Doom as HP deal 50% less damage.", "rarity": "Shop Relic"},
    "UNSETTLING_LAMP": {"name": "Unsettling Lamp", "description": "Each combat, the first time you play a card that Debuffs an enemy, double its effect.", "rarity": "Rare Relic"},
    "VAJRA": {"name": "Vajra", "description": "Start each combat with 1 Strength.", "rarity": "Common Relic"},
    "VAMBRACE": {"name": "Vambrace", "description": "The first time you gain Block from a card each combat, double the amount gained.", "rarity": "Uncommon Relic"},
    "VELVET_CHOKER": {"name": "Velvet Choker", "description": "Gain [energy:1] at the start of each turn. You cannot play more than 6 cards per turn.", "rarity": "Ancient Relic"},
    "VENERABLE_TEA_SET": {"name": "Venerable Tea Set", "description": "Whenever you enter a Rest Site, start the next combat with an additional [energy:2].", "rarity": "Common Relic"},
    "VERY_HOT_COCOA": {"name": "Very Hot Cocoa", "description": "Start each combat with an additional [energy:4].", "rarity": "Ancient Relic"},
    "VEXING_PUZZLEBOX": {"name": "Vexing Puzzlebox", "description": "At the start of each combat, add a random card into your Hand. It costs 0[energy:1].", "rarity": "Rare Relic"},
    "VITRUVIAN_MINION": {"name": "Vitruvian Minion", "description": "Cards containing “Minion” deal double damage and gain double Block.", "rarity": "Shop Relic"},
    "WAR_HAMMER": {"name": "War Hammer", "description": "Whenever you kill an Elite, Upgrade 4 random cards.", "rarity": "Ancient Relic"},
    "WAR_PAINT": {"name": "War Paint", "description": "Upon pickup, Upgrade 2 random Skills.", "rarity": "Common Relic"},
    "WHETSTONE": {"name": "Whetstone", "description": "Upon pickup, Upgrade 2 random Attacks.", "rarity": "Common Relic"},
    "WHISPERING_EARRING": {"name": "Whispering Earring", "description": "Gain [energy:1] at the start of each turn. [red]Vakuu plays your first turn for you.[/red]", "rarity": "Ancient Relic"},
    "WHITE_BEAST_STATUE": {"name": "White Beast Statue", "description": "Potions always appear in combat rewards.", "rarity": "Rare Relic"},
    "WHITE_STAR": {"name": "White Star", "description": "Elites drop an additional Rare card reward.", "rarity": "Rare Relic"},
    "WING_CHARM": {"name": "Wing Charm", "description": "A random card in each card reward is Enchanted with [purple]Swift[/purple] 1.", "rarity": "Shop Relic"},
    "WONGOS_MYSTERY_TICKET": {"name": "Wongo's Mystery Ticket", "description": "Receive 3 random Relics after 5 combats.", "rarity": "Event Relic"},
    "WONGO_CUSTOMER_APPRECIATION_BADGE": {"name": "Wongo Customer Appreciation Badge", "description": "Does nothing.", "rarity": "Event Relic"},
    "YUMMY_COOKIE": {"name": "Yummy Cookie", "description": "Upon pickup, Upgrade 4 cards.", "rarity": "Ancient Relic"},
}
